name: 'Require Label'
description: "Configure your PRs to have a label"
inputs:
  filter:  # id of input
    description: 'List of valid labels'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bookmark'
  color: 'orange'