name: Check for required label

on:
  pull_request:
    types: [opened, labeled, unlabeled, edited, reopened]
  label:
    types: [*]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          github_secret: 'total secret'