name: Check for required label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  label:
    types: ['*']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    id: test2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          github_secret: 'total secret'