name: Check for required label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  label:
    types: ['*']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say 
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: No Filter
        id: hello
        uses: ./
      - name: No Filter
        id: hello
        uses: ./
        with:
          filter: testlabel,bug,enhancement